clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.ivy2
      - ./.coursier
    volumes:
      - /tmp/cache:/cache
    when:
      event: [push, deployment, tag]

  run-tests:
    image: gwiq/sbt-docker:1.2.4
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=./.coursier -Dsbt.ivy.home=./.ivy2 -Dfile.encoding=utf-8 -Dsbt.gigahorse=false test
    secrets:
      - source: aws_access_key_id
        target: aws_access_key_id
      - source: aws_secret_access_key
        target: aws_secret_access_key
      - source: aws_region
        target: aws_region
    when:
      event: push
      matrix:
        APP: core

  publish-maven-artifacts:
    image: gwiq/sbt-docker:1.2.4
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=./.coursier -Dsbt.ivy.home=./.ivy2 -Dfile.encoding=utf-8 mawex-${APP}/publish
    secrets:
      - source: aws_access_key_id
        target: aws_access_key_id
      - source: aws_secret_access_key
        target: aws_secret_access_key
      - source: aws_region
        target: aws_region
    when:
      event: [deployment, tag]
      matrix:
        APP:
          - api
          - core

  stage-docker-image:
    image: gwiq/sbt-docker:1.2.4
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=./.coursier -Dsbt.ivy.home=./.ivy2 -Dfile.encoding=utf-8 mawex-${APP}/docker:stage
    secrets:
      - source: aws_access_key_id
        target: aws_access_key_id
      - source: aws_secret_access_key
        target: aws_secret_access_key
      - source: aws_region
        target: aws_region
    when:
      event: [deployment, tag]
      matrix:
        APP:
          - core
          - example

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.ivy2
      - ./.coursier
    volumes:
      - /tmp/cache:/cache
    when:
      event: [push, deployment, tag]

  build-on-deploy:
    image: docker:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker:/root/.docker
    environment:
      - IMAGE_NAME=gwiq/mawex-${APP}
    secrets:
      - source: docker_user
        target: docker_user
      - source: docker_password
        target: docker_password
      - source: aws_access_key_id
        target: aws_access_key_id
      - source: aws_secret_access_key
        target: aws_secret_access_key
      - source: aws_region
        target: aws_region
    commands:
      - docker build -t local/$APP:$DRONE_COMMIT_SHA ./src/mawex-$APP/target/docker/stage
      - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - docker tag local/$APP:$DRONE_COMMIT_SHA $IMAGE_NAME:$DRONE_COMMIT_SHA
      - docker push $IMAGE_NAME:$DRONE_COMMIT_SHA
    when:
      event: deployment
      matrix:
        APP:
        - core
        - example

  build-on-tag:
    image: docker:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker:/root/.docker
    environment:
      - IMAGE_NAME=gwiq/mawex-${APP}
      - RELEASE=${DRONE_TAG##v}
    secrets:
      - source: docker_user
        target: docker_user
      - source: docker_password
        target: docker_password
      - source: aws_access_key_id
        target: aws_access_key_id
      - source: aws_secret_access_key
        target: aws_secret_access_key
      - source: aws_region
        target: aws_region
    commands:
      - docker build -t local/$APP:$RELEASE ./src/mawex-$APP/target/docker/stage
      - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - docker tag local/$APP:$RELEASE $IMAGE_NAME:$RELEASE
      - docker push $IMAGE_NAME:$RELEASE
    when:
      branch: master
      event: tag
      matrix:
        APP:
        - core
        - example

matrix:
  APP:
  - api
  - core
  - example
