clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:

  run-tests:
    image: gwiq/sbt-docker:latest
    volumes:
      - /var/lib/docker/sbt:/cache
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=/cache/.coursier -Dsbt.ivy.home=/cache/.ivy2 -Divy.home=/cache/.ivy2 -Dfile.encoding=utf-8 -Dsbt.gigahorse=false test
    when:
      event: push

  publish-artifacts-and-stage-image:
    image: gwiq/sbt-docker:latest
    volumes:
      - /var/lib/docker/sbt:/cache
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=/cache/.coursier -Dsbt.ivy.home=/cache/.ivy2 -Divy.home=/cache/.ivy2 -Dfile.encoding=utf-8 mawex-api/publish mawex-core/publish mawex-core/docker:stage
    secrets: [ bintray_user, bintray_pass ]
    when:
      event: [deployment, tag]

  build-on-deploy:
    image: docker:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker:/root/.docker
    environment:
      - IMAGE_NAME=gwiq/mawex-core
    secrets: [ docker_user, docker_password ]
    commands:
      - docker build -t local/mawex-core:$DRONE_COMMIT_SHA ./src/core/target/docker/stage
      - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - docker tag local/mawex-core:$DRONE_COMMIT_SHA $IMAGE_NAME:$DRONE_COMMIT_SHA
      - docker push $IMAGE_NAME:$DRONE_COMMIT_SHA
    when:
      event: deployment

  build-on-tag:
    image: docker:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker:/root/.docker
    environment:
      - IMAGE_NAME=gwiq/mawex-core
      - RELEASE=${DRONE_TAG##v}
    secrets: [ docker_user, docker_password ]
    commands:
      - docker build -t local/mawex-core:$RELEASE ./src/core/target/docker/stage
      - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - docker tag local/mawex-core:$RELEASE $IMAGE_NAME:$RELEASE
      - docker push $IMAGE_NAME:$RELEASE
    when:
      branch: master
      event: tag
