sudo: required
os:
  - linux
services:
  - docker
language: scala
scala:
  - 2.12.6
jdk:
  - anapsix/alpine-java:8u144b01_jdk_unlimited
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - liska.jakub@gmail.com
before_script:
  - rm -rf ${HOME}/.sbt/1.0/staging
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean Mawex-core/test