version: '2'
services:

    redis:
        image: redis
        ports:
            - 6379:6379

    # master system uses akka cluster Singleton and akka persistence so that if if master-a crashes then master-b takes over

    master-a:
        image: gwiq/mawex:latest
        ports:
            - 2552:2552
        depends_on:
            - redis
        environment:
            - REDIS_PASSWORD=foo
        command: master --redis-address=redis:6379 --host-address=master-a:2552 --seed-nodes=master-a:2552,master-b:2551

    master-b:
        image: gwiq/mawex:latest
        ports:
            - 2551:2551
        depends_on:
            - redis
        environment:
            - REDIS_PASSWORD=foo
        command: master --redis-address=redis:6379 --host-address=master-b:2551 --seed-nodes=master-a:2552,master-b:2551

    workers:
        image: gwiq/mawex-example-worker:latest
        depends_on:
            - master-a
            - master-b
        command: workers --host-address=workers:0 --seed-nodes=master-a:2552,master-b:2551 --sandbox-jvm-opts=-Xmx64m gwi.mawex.ExampleExecutor gwi.mawex.ExampleCommandBuilder --foo=bar

    client:
        image: gwiq/mawex-example-client:latest
        depends_on:
            - workers
        command: --host-address=client:0 --seed-nodes=master-a:2552,master-b:2551