version: '2'
services:

    mawex:
        image: gwiq/mawex:latest
        restart: unless-stopped
        environment:
            - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true -Xmx128m

    redis:
        image: redis
        restart: unless-stopped
        ports:
            - 6379:6379

    master:
        extends:
          service: mawex
        ports:
            - 2552:2552
        depends_on:
            - redis
        environment:
            - REDIS_HOST=localhost
            - REDIS_PORT=6379
            - REDIS_PASSWORD=foo
        command: master --host-name=master

    workers:
        extends:
          service: mawex
        depends_on:
            - master
        command: workers --host-name=workers
