version: '2'
services:

    dynamo:
        image: dwmkerr/dynamodb
        ports:
            - 8000:8000
        command: -sharedDb

    dynamo-init:
        image: garland/aws-cli-docker
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=eu-west-1
        depends_on:
            - dynamo
        command: aws
                  --endpoint-url=http://dynamo:8000 dynamodb create-table
                  --table-name akka-persistence
                  --attribute-definitions
                      AttributeName=par,AttributeType=S
                      AttributeName=num,AttributeType=N
                  --key-schema AttributeName=par,KeyType=HASH AttributeName=num,KeyType=RANGE
                  --provisioned-throughput ReadCapacityUnits=1000,WriteCapacityUnits=1000

    # master system uses akka cluster Singleton and akka persistence so that if if master-a crashes then master-b takes over

    master-a:
        image: gwiq/mawex:latest
        ports:
            - 2552:2552
        depends_on:
            - dynamo-init
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: master --dynamo-endpoint=http://dynamo:8000 --host-address=master-a:2552 --seed-nodes=master-a:2552,master-b:2551

    master-b:
        image: gwiq/mawex:latest
        ports:
            - 2551:2551
        depends_on:
            - dynamo-init
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: master --dynamo-endpoint=http://dynamo:8000 --host-address=master-b:2551 --seed-nodes=master-a:2552,master-b:2551

    workers:
        image: gwiq/mawex-example-worker:latest
        depends_on:
            - master-a
            - master-b
        command: workers --host-address=workers:0 --seed-nodes=master-a:2552,master-b:2551 --sandbox-jvm-opts=-Xmx64m gwi.mawex.ExampleExecutor gwi.mawex.ExampleCommandBuilder --foo=bar

    client:
        image: gwiq/mawex-example-client:latest
        depends_on:
            - workers
        command: --host-address=client:0 --seed-nodes=master-a:2552,master-b:2551