version: '2'
services:

    redis:
        image: redis
        ports:
            - 6379:6379

    # master system uses akka cluster Singleton and akka persistence so that if if master-a crashes then master-b takes over

    master-a:
        image: gwiq/mawex:latest
        ports:
            - 2552:2552
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=foo
        command: master --host-address=master-a:2552 --seed-nodes=master-a:2552,master-b:2551

    master-b:
        image: gwiq/mawex:latest
        ports:
            - 2551:2551
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=foo
        command: master --host-address=master-b:2551 --seed-nodes=master-a:2552,master-b:2551

    # note that this container contains also a client service in example.Executor which doesn't make sense in real world where it would reside in its own container
    # I used to have a client docker container with a sample app but there was just too much boilerplate code to maintain, see example.Executor
    workers:
        image: gwiq/mawex-example-worker:latest
        depends_on:
            - master-a
            - master-b
        command: workers --host-address=workers:0 --seed-nodes=master-a:2552,master-b:2551 example.Executor