version: '2'
services:

    mawex:
        image: gwiq/mawex-example:latest
        environment:
            - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true -Xmx128m

    redis:
        image: redis
        ports:
            - 6379:6379

    master:
        extends:
          service: mawex
        ports:
            - 2552:2552
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=foo
        command: master-with-local-client

    workers:
        extends:
          service: mawex
        command: workers
