version: '2'
services:

    mawex:
        image: gwiq/mawex-example:latest
        environment:
            - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true -Xmx128m

    master:
        extends:
          service: mawex
        ports:
            - 2552:2552
        command: master-with-local-client

    workers:
        extends:
          service: mawex
        command: workers
