version: '2'
services:

    persitence:
        image: redis
        ports:
            - 6379:6379

    master-a:
        environment:
          - JAVA_TOOL_OPTIONS=-Dconfig.resource=redis.conf

    master-b:
        environment:
          - JAVA_TOOL_OPTIONS=-Dconfig.resource=redis.conf
